[package]
name = "oxide_kv"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = { version = "0.4.28", features = ["max_level_debug", "release_max_level_warn"] }
env_logger = "0.11.8"
serde_json = "1.0.145"
